name: homelyknock
description: A new Flutter project.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=2.19.6 <3.10.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dots_indicator: ^2.0.0
  carousel_slider: ^4.0.0
  google_fonts: ^4.0.3
  dropdown_button2: ^1.9.4
  flutter_verification_code: ^1.1.6
  flutter_countdown_timer: ^4.1.0
  persistent_bottom_nav_bar:
  
  flutter_screenutil: ^5.7.0
  http: ^0.13.5
  fluttertoast: ^8.2.1
  shared_preferences: ^2.0.18
  percent_indicator: ^4.2.3
  smooth_page_indicator: ^1.0.1
  dropdown_search: ^5.0.6
  flutter_switch: ^0.3.2
  get: ^4.6.5
  google_maps_flutter: ^2.2.5
  intl: ^0.18.0
  dart_code_metrics: ^5.7.0       # added by abir
  logger:                         # added by abir
  flutter_widget_from_html: ^0.10.0
  jiffy: ^6.1.0

  image_picker: ^0.8.7+3
  flutter_rating_bar: ^4.0.1
  

  shimmer: ^2.0.0        # added by abir
  url_launcher: ^6.1.10
  flutter_typeahead: ^4.3.8
  geocoding: ^2.1.0
  connectivity_plus: ^3.0.6
  intl_phone_field: ^3.1.0



dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

#  flutter_launcher_icons:       # added by abir
#flutter pub run flutter_launcher_icons:main
  #flutter_app_name: ^0.1.1
#flutter pub run flutter_app_name

# flutter_app_name:
#   name: "Hire Do"

#flutter_icons:                  # added by abir
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/Logo/escroc_launcher_icon.png"

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/icons/