String baseUrl = "http://ringknock.pythonanywhere.com/";
String signupApi = "${baseUrl}register/";
String signInApi = "${baseUrl}login/";
String leadcategory = "${baseUrl}lead/category/";
String addService = "${baseUrl}services/";
String fetchService = "${baseUrl}services/";
String addLocation = "${baseUrl}locations/";
String fetchLocation = "${baseUrl}locations/";
String sliderApi="${baseUrl}slider/";
